# 公開するページのURL
baseURL = "https://tomoyasuzuki.github.io."

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "my-tech-blog"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Tomoya Suzuki"
    bio = "Software Engineer"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "oshiborii"
  github = "tomoyasuzuki"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

